### ISSUE TITLE
ATTR_COLOR_TEMP deprecation in 2026.1

### ISSUE THREAD

**Issue by jens-vonberg** [QNimbus/haefele-connect-mesh#3]
My log in Home Assistant is showing the folliowing error:

Logger: homeassistant.components.light
Source: helpers/deprecation.py:257
integration: Light (documentation, issues)
First occurred: 08:08:21 (2 occurrences)
Last logged: 08:08:21

The deprecated constant ATTR_COLOR_TEMP was used from haefele_connect_mesh. It will be removed in HA Core 2026.1. Use kelvin equivalent (ATTR_COLOR_TEMP_KELVIN) instead, please report it to the author of the 'haefele_connect_mesh' custom integration

It would be nice if the integration would still work in 2026.1.

Thank you in advance for your great integration.

**Comment by jens-vonberg** [comment]
Since 2026.03 the Integration is not working anymore with the following error:
Failed setup, will retry: cannot import name 'ATTR_COLOR_TEMP' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

**Comment by qnimbus** [comment]
Hi @jens-vonberg  — thanks for the detailed report. 

This has been fixed in the current main branch. The changes include:                                                                                                                                                                                                                                                                                                         
- ATTR_COLOR_TEMP → ATTR_COLOR_TEMP_KELVIN                                                                                                                                                                                                                                                                                                                                   
- color_temp property (mireds) → color_temp_kelvin property (Kelvin)                                                                                                                                                                                                                                                                                                         
- _attr_min_mireds / _attr_max_mireds → _attr_min_color_temp_kelvin / _attr_max_color_temp_kelvin

edit: The fix is in the current [v2.0.3-beta.6](https://github.com/qnimbus/haefele-connect-mesh/releases/tag/v2.0.3-beta.6)                                                                                                                                                                                                                                                                                                                                                                                                                                           release
